CREATE  DATABASE PALACE

USE PALACE

CREATE TABLE MEALS
(
    ID INT PRIMARY KEY IDENTITY,
    NAME NVARCHAR(50),
    PRICE MONEY
)
ALTER TABLE MEALS
ALTER COLUMN NAME NVARCHAR(50) NOT NULL;

SELECT * FROM MEALS

CREATE TABLE TABLES
(
    ID BIGINT PRIMARY KEY IDENTITY,
    NO NVARCHAR(50),
)
ALTER TABLE TABLES
ALTER COLUMN NO NVARCHAR(50) NOT NULL

SELECT * FROM TABLES

CREATE TABLE ORDERS
(
    ID  INT PRIMARY KEY IDENTITY,
    MEALID INT  FOREIGN KEY REFERENCES MEALS(ID),
    TABLEID BIGINT FOREIGN KEY REFERENCES  TABLES(ID),
    DATETIME DATETIME2 
)

INSERT INTO MEALS(NAME,PRICE)
VALUES
(N'KABAB',26),
(N'XENGEL',21),
(N'DUSBERE',15),
(N'STALICNI',6),
(N'PIZZA',12)

SELECT * FROM MEALS

INSERT INTO TABLES
VALUES
('NO1'),
('NO2'),
('NO3'),
('NO4'),
('NO5')

INSERT INTO ORDERS(MEALID,TABLEID,DATETIME)
VALUES
(2,2,'2022-01-04 13:00'),
(5,2,'2023-01-04 20:00'),
(4,5,'2023-01-06 20:00'),
(3,3,'2023-01-04 12:00'),
(3,2,'2023-01-04 13:00')


--Bütün masadatalarını yanında o masaya edilmiş sifariş sayı ilə birlikdə select edən query

SELECT *,(SELECT COUNT(*) FROM ORDERS AS O WHERE O.TABLEID=T.ID) AS ORDERCOUNT FROM TABLES AS T

--Bütün yeməkləri o yeməyin sifariş sayı ilə select edən query

SELECT *,(SELECT COUNT(*) FROM ORDERS AS O WHERE O.MEALID=M.ID ) AS ORDERCOUNT FROM MEALS AS M 

--Bütün sirafiş datalarını yanında yeməyin adı ilə select edən query

SELECT * ,(SELECT M.NAME FROM MEALS AS M WHERE M.ID=O.MEALID) AS MEALNAME FROM ORDERS AS O

--Bütün sirafiş datalarını yanında yeməyin adı və masanın nömrəsi  ilə select edən query

SELECT * ,(SELECT M.NAME FROM MEALS AS M WHERE M.ID=O.MEALID) AS MEALNAME ,
(SELECT T.NO FROM TABLES AS T WHERE T.ID=O.TABLEID) AS TABLENO  FROM ORDERS AS O

--Bütün masa datalarını yanında o masının sifarişlərinin ümumi məbləği ilə select edən query 

SELECT * ,(SELECT SUM(M.PRICE) FROM ORDERS AS O JOIN MEALS AS M ON O.MEALID=M.ID 
WHERE O.TABLEID=T.ID) AS UMUMIMEBLEG FROM TABLES AS T

--1-idli masaya verilmis ilk sifarişlə son sifariş arasında neçə saat fərq olduğunu select edən query
--MENDE ID 2 DEN BASLAYIR DEYE 2 YI HESABLADIM;)

SELECT 
    DATEDIFF(HOUR, 
    (SELECT MIN(DATETIME) FROM ORDERS WHERE TABLEID = 2), 
      (SELECT MAX(DATETIME) FROM ORDERS WHERE TABLEID = 2)
    ) AS DATEDIFFFORID

--ən son 30-dəqədən əvvəl verilmiş sifarişləri select edən query

SELECT *FROM ORDERS WHERE DATEDIFF(MINUTE, DATETIME, GETDATE()) <= 30

--heç sifariş verməmiş masaları select edən query

SELECT * FROM TABLES AS T WHERE NOT EXISTS ( SELECT *  FROM ORDERS AS O  WHERE O.TABLEID = T.ID)

--son 60 dəqiqədə heç sifariş verməmiş masaları select edən query

SELECT * FROM TABLES AS T
WHERE NOT EXISTS ( SELECT *  FROM ORDERS AS O WHERE O.TABLEID = T.ID AND DATEDIFF(MINUTE,O.DATETIME,GETDATE())<=60)
